source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1.3"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "mysql2", "~> 0.5.6"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

gem "jwt", "~> 2.8"

gem "bcrypt", "~> 3.1"
