version: "3"

services:
  db:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=online_chess
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
        - -u
        - root
        - -p$$MYSQL_ROOT_PASSWORD
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s
  app:
    build: online_chess_backend
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    volumes:
      - ./online_chess_backend:/src
    depends_on:
      db:
        condition: service_healthy
